--------------------------------------------------------------------------------
-- ORAHomer :: table HOM_LOG
--------------------------------------------------------------------------------
-- Central application log. Written only by PCK_HOM_LOG (which logs via an
-- autonomous transaction so entries survive a rollback of the calling unit).
--------------------------------------------------------------------------------

create table hom_log (
  log_id        number generated by default as identity
                   constraint hom_log_pk primary key,
  log_level     varchar2(10)  not null,            -- ERROR | WARN | INFO | DEBUG
  package_name  varchar2(128),
  routine_name  varchar2(128),
  message       clob,
  --- audit (auto-populated by PCK_HOM_LOG when passed NULL) --------------------
  created_at    timestamp     default systimestamp,
  created_by    varchar2(128) default user,
  updated_at    timestamp     default systimestamp,
  updated_by    varchar2(128) default user,
  constraint hom_log_level_ck check (log_level in ('ERROR','WARN','INFO','DEBUG'))
)
lob (message) store as securefile (enable storage in row);

create index hom_log_ts_ix on hom_log (created_at);

comment on table  hom_log           is 'ORAHomer central log. Written only by PCK_HOM_LOG (autonomous transaction).';
comment on column hom_log.log_level is 'ERROR | WARN | INFO | DEBUG.';
comment on column hom_log.message   is 'Free-text log message.';
