--------------------------------------------------------------------------------
-- ORAHomer :: table HOM_LINKS
--------------------------------------------------------------------------------
-- External link tiles. These appear on the homepage alongside the workspace apps
-- and can be categorised and icon-customised the same way. All DML goes through
-- PCK_HOM_LINKS_DML.
--------------------------------------------------------------------------------

create table hom_links (
  link_id          number generated by default as identity
                     constraint hom_links_pk primary key,
  title            varchar2(255)  not null,
  url              varchar2(4000) not null,
  description      varchar2(400),
  category_id      number,
  icon_id          number,                              -- uploaded icon (HOM_ICONS); else a generated badge
  open_in_new_tab  varchar2(1)    default 'Y' not null, -- target _blank when 'Y'
  is_visible       varchar2(1)    default 'Y' not null, -- 'N' hides the link from the homepage
  display_seq      number         default 10 not null,  -- ordering within its category
  --- audit (auto-populated by PCK_HOM_LINKS_DML when passed NULL) --------------
  created_at       timestamp      default systimestamp,
  created_by       varchar2(128)  default user,
  updated_at       timestamp      default systimestamp,
  updated_by       varchar2(128)  default user,
  constraint hom_links_newtab_ck  check (open_in_new_tab in ('Y','N')),
  constraint hom_links_visible_ck check (is_visible in ('Y','N')),
  constraint hom_links_cat_fk  foreign key (category_id) references hom_categories (category_id),
  constraint hom_links_icon_fk foreign key (icon_id)     references hom_icons (icon_id)
);

create index hom_links_cat_ix  on hom_links (category_id);
create index hom_links_icon_ix on hom_links (icon_id);

comment on table  hom_links                 is 'ORAHomer external link tiles. DML only via PCK_HOM_LINKS_DML.';
comment on column hom_links.title           is 'Tile title.';
comment on column hom_links.url             is 'Target URL (absolute, e.g. https://...).';
comment on column hom_links.description     is 'Optional tile subtitle.';
comment on column hom_links.category_id     is 'Optional category the link is grouped under.';
comment on column hom_links.icon_id         is 'Optional uploaded icon (HOM_ICONS); without it a badge is generated from the title.';
comment on column hom_links.open_in_new_tab is 'Y = open in a new browser tab.';
comment on column hom_links.is_visible      is 'Y = shown on the homepage; N = hidden.';
comment on column hom_links.display_seq     is 'Sort order within the category (ascending).';
