--------------------------------------------------------------------------------
-- ORAHomer :: table HOM_ICONS
--------------------------------------------------------------------------------
-- Reusable icon library. Upload an image once and assign it to any number of
-- apps or external links as a replacement for the (auto-detected) APEX app icon.
-- The homepage renders the BLOB directly as the card media. All DML goes through
-- PCK_HOM_ICONS_DML.
--------------------------------------------------------------------------------

create table hom_icons (
  icon_id     number generated by default as identity
                 constraint hom_icons_pk primary key,
  name        varchar2(100)  not null
                 constraint hom_icons_name_uk unique,
  file_name   varchar2(255),
  mime_type   varchar2(100)  not null,
  icon_blob   blob           not null,
  --- audit (auto-populated by PCK_HOM_ICONS_DML when passed NULL) --------------
  created_at  timestamp      default systimestamp,
  created_by  varchar2(128)  default user,
  updated_at  timestamp      default systimestamp,
  updated_by  varchar2(128)  default user
)
lob (icon_blob) store as securefile;

comment on table  hom_icons            is 'ORAHomer reusable icon library (uploaded images). DML only via PCK_HOM_ICONS_DML.';
comment on column hom_icons.name       is 'Unique label shown in the icon pick lists.';
comment on column hom_icons.file_name  is 'Original uploaded file name.';
comment on column hom_icons.mime_type  is 'Image MIME type, e.g. image/png or image/svg+xml.';
comment on column hom_icons.icon_blob  is 'The image bytes, rendered as the homepage card media.';
