--------------------------------------------------------------------------------
-- ORAHomer :: table HOM_CATEGORIES
--------------------------------------------------------------------------------
-- Categories used to group the homepage tiles (apps and external links). Tiles
-- reference a category; uncategorised tiles fall into a virtual bucket rendered
-- last. All DML goes through PCK_HOM_CATEGORIES_DML.
--------------------------------------------------------------------------------

create table hom_categories (
  category_id    number generated by default as identity
                   constraint hom_categories_pk primary key,
  name           varchar2(100)  not null
                   constraint hom_categories_name_uk unique,
  icon_css       varchar2(100),                       -- optional Font APEX class for the section badge
  display_seq    number         default 10 not null,  -- ordering of categories on the homepage
  is_active      varchar2(1)    default 'Y' not null, -- 'N' hides the whole category
  --- audit (auto-populated by PCK_HOM_CATEGORIES_DML when passed NULL) ---------
  created_at     timestamp      default systimestamp,
  created_by     varchar2(128)  default user,
  updated_at     timestamp      default systimestamp,
  updated_by     varchar2(128)  default user,
  constraint hom_categories_active_ck check (is_active in ('Y','N'))
);

comment on table  hom_categories             is 'ORAHomer tile categories. DML only via PCK_HOM_CATEGORIES_DML.';
comment on column hom_categories.name        is 'Unique category label shown as the tile group / badge.';
comment on column hom_categories.icon_css    is 'Optional Font APEX class (e.g. fa-folder) for the category badge.';
comment on column hom_categories.display_seq is 'Sort order of the category on the homepage (ascending).';
comment on column hom_categories.is_active   is 'Y = shown; N = the whole category and its tiles are hidden.';
