--------------------------------------------------------------------------------
-- ORAHomer :: PCK_HOM_API  (read-side helpers for the homepage)
--------------------------------------------------------------------------------
-- Pure read helpers used by the HOM_*_V views and the APEX pages. The heart is
-- the icon resolution chain used to render every tile as a single BLOB so the
-- APEX "Cards" media (source = BLOB column) renders uniformly:
--
--   1. uploaded icon  (HOM_ICONS.icon_id assigned to the app/link)   -> that image
--   2. AUTO app icon  (the app's own icon static file, any workspace app)
--   3. generated SVG  (a coloured badge with the tile's initials)    -> fallback
--
-- The app icon is read from APEX_APPLICATION_STATIC_FILES (icons/app-icon-*.png,
-- generated by APEX when an application icon is configured). Reads only; never
-- commits. AUTHID DEFINER so the views resolve as the owning schema.
--------------------------------------------------------------------------------

create or replace package pck_hom_api
  authid definer
as
  c_pkg constant varchar2(30) := 'PCK_HOM_API';

  -- The app's own icon image (best available size), or NULL when the app has no
  -- configured application icon.
  function app_icon_blob(p_application_id in number) return blob;

  -- A generated, deterministic coloured SVG badge showing the tile initials.
  function svg_badge(p_label in varchar2) return blob;

  -- Resolved tile icon as a BLOB (chain above) and its MIME type.
  function tile_icon_blob(p_icon_id in number, p_application_id in number, p_label in varchar2) return blob;
  function tile_icon_mime(p_icon_id in number, p_application_id in number) return varchar2;

  -- Relative URL that opens an app at its home page.
  function app_url(p_application_id in number) return varchar2;
end pck_hom_api;
/

create or replace package body pck_hom_api
as

  function app_icon_blob(p_application_id in number) return blob is
    l_blob blob;
  begin
    -- Prefer the medium square icon; fall back through the other generated sizes.
    select file_content
      into l_blob
      from (
        select file_content,
               case file_name
                 when 'icons/app-icon-192.png'         then 1
                 when 'icons/app-icon-256-rounded.png' then 2
                 when 'icons/app-icon-512.png'         then 3
                 when 'icons/app-icon-144-rounded.png' then 4
                 when 'icons/app-icon-32.png'          then 5
                 else 9
               end as pref
          from apex_application_static_files
         where application_id = p_application_id
           and file_name like 'icons/app-icon%'
         order by pref
      )
     where rownum = 1;
    return l_blob;
  exception
    when no_data_found then
      return null;
    when others then
      -- never let icon discovery break the homepage; degrade to the badge
      pck_hom_log.warn(c_pkg, 'app_icon_blob', 'app ' || p_application_id || ': ' || sqlerrm);
      return null;
  end app_icon_blob;


  function svg_badge(p_label in varchar2) return blob is
    l_clean varchar2(400);
    l_w1    varchar2(100);
    l_w2    varchar2(100);
    l_text  varchar2(4);
    l_hue   pls_integer;
    l_svg   varchar2(2000);
    l_raw   raw(4000);
    l_blob  blob;
  begin
    l_clean := trim(regexp_replace(nvl(p_label, '?'), '\s+', ' '));
    l_w1    := regexp_substr(l_clean, '\S+', 1, 1);
    l_w2    := regexp_substr(l_clean, '\S+', 1, 2);
    l_text  := upper(substr(l_w1, 1, 1));
    if l_w2 is not null then
      l_text := l_text || upper(substr(l_w2, 1, 1));
    end if;
    if l_text is null then
      l_text := '?';
    end if;

    l_hue := mod(dbms_utility.get_hash_value(upper(l_clean), 0, 360), 360);

    l_svg := '<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160">'
          || '<rect width="160" height="160" rx="32" fill="hsl(' || l_hue || ',52%,46%)"/>'
          || '<text x="80" y="84" font-family="Arial,Helvetica,sans-serif" font-size="'
          || case when length(l_text) > 1 then '66' else '82' end
          || '" font-weight="600" fill="#ffffff" text-anchor="middle" '
          || 'dominant-baseline="central">' || l_text || '</text></svg>';

    l_raw := utl_raw.cast_to_raw(l_svg);
    dbms_lob.createtemporary(l_blob, true);
    dbms_lob.writeappend(l_blob, utl_raw.length(l_raw), l_raw);
    return l_blob;
  end svg_badge;


  function tile_icon_blob(p_icon_id in number, p_application_id in number, p_label in varchar2) return blob is
    l_blob blob;
  begin
    if p_icon_id is not null then
      begin
        select icon_blob into l_blob from hom_icons where icon_id = p_icon_id;
        return l_blob;
      exception
        when no_data_found then null;  -- icon was deleted; fall through
      end;
    end if;

    if p_application_id is not null then
      l_blob := app_icon_blob(p_application_id);
      if l_blob is not null and dbms_lob.getlength(l_blob) > 0 then
        return l_blob;
      end if;
    end if;

    return svg_badge(p_label);
  end tile_icon_blob;


  function tile_icon_mime(p_icon_id in number, p_application_id in number) return varchar2 is
    l_mime hom_icons.mime_type%type;
    l_blob blob;
  begin
    if p_icon_id is not null then
      begin
        select mime_type into l_mime from hom_icons where icon_id = p_icon_id;
        return l_mime;
      exception
        when no_data_found then null;
      end;
    end if;

    if p_application_id is not null then
      l_blob := app_icon_blob(p_application_id);
      if l_blob is not null and dbms_lob.getlength(l_blob) > 0 then
        return 'image/png';
      end if;
    end if;

    return 'image/svg+xml';
  end tile_icon_mime;


  function app_url(p_application_id in number) return varchar2 is
  begin
    return 'f?p=' || p_application_id;
  end app_url;

end pck_hom_api;
/
