--------------------------------------------------------------------------------
-- ORAHomer :: PCK_HOM_API  (read-side helpers for the homepage)
--------------------------------------------------------------------------------
-- Pure read helpers used by the HOM_*_V views and the APEX pages. The heart is
-- the icon resolution chain used to render every tile as a single BLOB so the
-- APEX "Cards" media (source = BLOB column) renders uniformly:
--
--   1. uploaded icon  (HOM_ICONS.icon_id assigned to the app/link)   -> that image
--   2. AUTO app icon  (the app's own icon static file, any workspace app)
--   3. generated SVG  (a coloured badge with the tile's initials)    -> fallback
--
-- The app icon is read from APEX_APPLICATION_STATIC_FILES (icons/app-icon-*.png,
-- generated by APEX when an application icon is configured). Reads only; never
-- commits. AUTHID DEFINER so the views resolve as the owning schema.
--------------------------------------------------------------------------------

create or replace package pck_hom_api
  authid definer
as
  c_pkg constant varchar2(30) := 'PCK_HOM_API';

  -- The app's own icon image (best available size), or NULL when the app has no
  -- configured application icon.
  function app_icon_blob(p_application_id in number) return blob;

  -- A generated, deterministic coloured SVG badge showing the tile initials.
  function svg_badge(p_label in varchar2) return blob;

  -- Resolved tile icon as a BLOB (chain above) and its MIME type.
  function tile_icon_blob(p_icon_id in number, p_application_id in number, p_label in varchar2) return blob;
  function tile_icon_mime(p_icon_id in number, p_application_id in number) return varchar2;

  -- Relative URL that opens an app at its home page.
  function app_url(p_application_id in number) return varchar2;

  -- Full homepage markup (HOM_TILES_V grouped by category): a heading per
  -- category followed by its tiles, ordered by category then tile sequence.
  -- Each tile is one clickable card (icon left, name + description right). Icons
  -- are inlined as data-URIs so no extra BLOB-streaming endpoint is needed.
  -- Returned by the page-1 "dynamicContent" region (plsqlFunctionBody).
  function render_home return clob;
end pck_hom_api;
/

create or replace package body pck_hom_api
as

  function app_icon_blob(p_application_id in number) return blob is
    l_blob blob;
  begin
    -- Prefer the medium square icon; fall back through the other generated sizes.
    select file_content
      into l_blob
      from (
        select file_content,
               case file_name
                 when 'icons/app-icon-192.png'         then 1
                 when 'icons/app-icon-256-rounded.png' then 2
                 when 'icons/app-icon-512.png'         then 3
                 when 'icons/app-icon-144-rounded.png' then 4
                 when 'icons/app-icon-32.png'          then 5
                 else 9
               end as pref
          from apex_application_static_files
         where application_id = p_application_id
           and file_name like 'icons/app-icon%'
         order by pref
      )
     where rownum = 1;
    return l_blob;
  exception
    when no_data_found then
      return null;
    when others then
      -- never let icon discovery break the homepage; degrade to the badge
      pck_hom_log.warn(c_pkg, 'app_icon_blob', 'app ' || p_application_id || ': ' || sqlerrm);
      return null;
  end app_icon_blob;


  function svg_badge(p_label in varchar2) return blob is
    l_clean varchar2(400);
    l_w1    varchar2(100);
    l_w2    varchar2(100);
    l_text  varchar2(4);
    l_hue   pls_integer;
    l_svg   varchar2(2000);
    l_raw   raw(4000);
    l_blob  blob;
  begin
    l_clean := trim(regexp_replace(nvl(p_label, '?'), '\s+', ' '));
    l_w1    := regexp_substr(l_clean, '\S+', 1, 1);
    l_w2    := regexp_substr(l_clean, '\S+', 1, 2);
    l_text  := upper(substr(l_w1, 1, 1));
    if l_w2 is not null then
      l_text := l_text || upper(substr(l_w2, 1, 1));
    end if;
    if l_text is null then
      l_text := '?';
    end if;

    l_hue := mod(dbms_utility.get_hash_value(upper(l_clean), 0, 360), 360);

    l_svg := '<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160">'
          || '<rect width="160" height="160" rx="32" fill="hsl(' || l_hue || ',52%,46%)"/>'
          || '<text x="80" y="84" font-family="Arial,Helvetica,sans-serif" font-size="'
          || case when length(l_text) > 1 then '66' else '82' end
          || '" font-weight="600" fill="#ffffff" text-anchor="middle" '
          || 'dominant-baseline="central">' || l_text || '</text></svg>';

    l_raw := utl_raw.cast_to_raw(l_svg);
    dbms_lob.createtemporary(l_blob, true);
    dbms_lob.writeappend(l_blob, utl_raw.length(l_raw), l_raw);
    return l_blob;
  end svg_badge;


  function tile_icon_blob(p_icon_id in number, p_application_id in number, p_label in varchar2) return blob is
    l_blob blob;
  begin
    if p_icon_id is not null then
      begin
        select icon_blob into l_blob from hom_icons where icon_id = p_icon_id;
        return l_blob;
      exception
        when no_data_found then null;  -- icon was deleted; fall through
      end;
    end if;

    if p_application_id is not null then
      l_blob := app_icon_blob(p_application_id);
      if l_blob is not null and dbms_lob.getlength(l_blob) > 0 then
        return l_blob;
      end if;
    end if;

    return svg_badge(p_label);
  end tile_icon_blob;


  function tile_icon_mime(p_icon_id in number, p_application_id in number) return varchar2 is
    l_mime hom_icons.mime_type%type;
    l_blob blob;
  begin
    if p_icon_id is not null then
      begin
        select mime_type into l_mime from hom_icons where icon_id = p_icon_id;
        return l_mime;
      exception
        when no_data_found then null;
      end;
    end if;

    if p_application_id is not null then
      l_blob := app_icon_blob(p_application_id);
      if l_blob is not null and dbms_lob.getlength(l_blob) > 0 then
        return 'image/png';
      end if;
    end if;

    return 'image/svg+xml';
  end tile_icon_mime;


  function app_url(p_application_id in number) return varchar2 is
  begin
    return 'f?p=' || p_application_id;
  end app_url;


  --- append a VARCHAR2 fragment to a CLOB buffer -------------------------------
  procedure app(p_buf in out nocopy clob, p_txt in varchar2) is
  begin
    if p_txt is not null then
      dbms_lob.writeappend(p_buf, length(p_txt), p_txt);
    end if;
  end app;


  --- continuous (newline-free) base64 of a BLOB, for data: URIs ----------------
  function blob_to_b64(p_blob in blob) return clob is
    l_out   clob;
    l_chunk constant pls_integer := 2400;   -- multiple of 3 => clean base64 chunks
    l_pos   integer := 1;
    l_len   integer := dbms_lob.getlength(p_blob);
    l_raw   raw(2400);
    l_b64   varchar2(4000);
  begin
    dbms_lob.createtemporary(l_out, true);
    while l_pos <= l_len loop
      l_raw := dbms_lob.substr(p_blob, l_chunk, l_pos);
      l_b64 := utl_raw.cast_to_varchar2(utl_encode.base64_encode(l_raw));
      l_b64 := replace(replace(l_b64, chr(13)), chr(10));
      dbms_lob.writeappend(l_out, length(l_b64), l_b64);
      l_pos := l_pos + l_chunk;
    end loop;
    return l_out;
  end blob_to_b64;


  function render_home return clob is
    l_html clob;
    l_cat  varchar2(255) := chr(0);   -- sentinel: no category emitted yet
    l_any  boolean := false;
  begin
    dbms_lob.createtemporary(l_html, true);

    -- Scoped, UT-friendly styling: own classes (no UT internals overridden),
    -- theme colours via UT CSS variables with safe fallbacks.
    app(l_html,
      '<style>'
      || '.hom-wrap{padding:4px 0 16px;}'
      || '.hom-cat{font-size:14px;font-weight:600;letter-spacing:.02em;text-transform:uppercase;'
      || 'color:var(--ut-body-text-color,#37424a);opacity:.75;margin:22px 2px 10px;}'
      || '.hom-cat:first-child{margin-top:6px;}'
      || '.hom-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(264px,1fr));gap:12px;}'
      || '.hom-card{display:flex;align-items:center;gap:14px;padding:14px 16px;border-radius:8px;'
      || 'text-decoration:none;background:var(--ut-component-background-color,#fff);'
      || 'border:1px solid var(--ut-component-border-color,rgba(0,0,0,.12));'
      || 'box-shadow:0 1px 2px rgba(0,0,0,.05);'
      || 'transition:box-shadow .15s ease,transform .15s ease,border-color .15s ease;}'
      || '.hom-card:hover,.hom-card:focus{box-shadow:0 6px 18px rgba(0,0,0,.13);transform:translateY(-2px);'
      || 'border-color:var(--ut-palette-primary,#0072b2);outline:none;}'
      || '.hom-media{flex:0 0 auto;width:48px;height:48px;display:flex;align-items:center;justify-content:center;}'
      || '.hom-media img{max-width:48px;max-height:48px;border-radius:8px;display:block;}'
      || '.hom-body{display:flex;flex-direction:column;min-width:0;}'
      || '.hom-title{font-weight:600;line-height:1.3;color:var(--ut-body-text-color,#37424a);'
      || 'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}'
      || '.hom-desc{font-size:12.5px;line-height:1.35;margin-top:2px;color:var(--ut-body-text-color,#37424a);'
      || 'opacity:.65;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;}'
      || '.hom-empty{color:var(--ut-body-text-color,#37424a);opacity:.65;padding:8px 2px;}'
      || '</style><div class="hom-wrap">');

    for r in (
      select tile_kind, ref_id, title, subtitle, url, new_tab,
             category_label, category_seq, display_seq, icon_blob, icon_mime
        from hom_tiles_v
       order by category_seq, category_label, display_seq, lower(title)
    ) loop
      l_any := true;

      -- new category heading + open a fresh grid
      if r.category_label <> l_cat or l_cat = chr(0) then
        if l_cat <> chr(0) then
          app(l_html, '</div>');               -- close previous grid
        end if;
        app(l_html, '<h2 class="hom-cat">' || apex_escape.html(r.category_label) || '</h2>');
        app(l_html, '<div class="hom-grid">');
        l_cat := r.category_label;
      end if;

      -- the whole card is the link
      app(l_html, '<a class="hom-card" href="' || apex_escape.html(r.url) || '"'
                  || case when r.new_tab = 'Y' then ' target="_blank" rel="noopener"' end || '>');

      app(l_html, '<span class="hom-media">');
      if r.icon_blob is not null and dbms_lob.getlength(r.icon_blob) > 0 then
        app(l_html, '<img alt="" loading="lazy" src="data:' || r.icon_mime || ';base64,');
        dbms_lob.append(l_html, blob_to_b64(r.icon_blob));
        app(l_html, '">');
      end if;
      app(l_html, '</span>');

      app(l_html, '<span class="hom-body"><span class="hom-title">' || apex_escape.html(r.title) || '</span>');
      if r.subtitle is not null then
        app(l_html, '<span class="hom-desc">' || apex_escape.html(r.subtitle) || '</span>');
      end if;
      app(l_html, '</span></a>');
    end loop;

    if l_any then
      app(l_html, '</div>');                    -- close last grid
    else
      app(l_html, '<p class="hom-empty">Es sind keine Anwendungen sichtbar.</p>');
    end if;

    app(l_html, '</div>');                       -- close .hom-wrap
    return l_html;
  end render_home;

end pck_hom_api;
/
