--------------------------------------------------------------------------------
-- ORAHomer :: update (recompile code without touching data)
--------------------------------------------------------------------------------
-- Re-runs the CREATE OR REPLACE packages and views (and re-seeds any missing
-- config keys) without dropping tables -- safe on an existing install with data.
-- Use after pulling package/view changes. For table changes, hand-write an
-- ALTER here or do a full @uninstall.sql + @install.sql.
--------------------------------------------------------------------------------

set define off
set serveroutput on size unlimited
set echo off
whenever sqlerror continue

prompt -- schema migrations (idempotent: bring an existing install up to date)
declare
  l_n number;

  procedure recreate_icon_fk(p_table in varchar2, p_cons in varchar2) is
    l_c number;
  begin
    select count(*) into l_c from user_constraints where constraint_name = upper(p_cons);
    if l_c > 0 then
      execute immediate 'alter table ' || p_table || ' drop constraint ' || p_cons;
    end if;
    execute immediate 'alter table ' || p_table || ' add constraint ' || p_cons ||
                      ' foreign key (icon_id) references hom_icons (icon_id) on delete set null';
  end recreate_icon_fk;
begin
  -- HOM_APP_CONFIG.description (added with the homepage redesign)
  select count(*) into l_n
    from user_tab_columns
   where table_name = 'HOM_APP_CONFIG' and column_name = 'DESCRIPTION';
  if l_n = 0 then
    execute immediate 'alter table hom_app_config add (description varchar2(400))';
    execute immediate q'[comment on column hom_app_config.description is 'Optional tile subtitle shown under the app name on the homepage.']';
  end if;

  -- icon FKs must be ON DELETE SET NULL so deleting an in-use icon via the
  -- APEX form (Automatic Row Processing) detaches referencing rows instead of
  -- raising an FK error.
  recreate_icon_fk('hom_app_config', 'hom_app_config_icon_fk');
  recreate_icon_fk('hom_links',      'hom_links_icon_fk');

  -- ON NULL so APEX form Automatic Row Processing (which inserts the PK column
  -- as NULL on create) lets the identity generate the value instead of failing.
  execute immediate 'alter table hom_icons modify icon_id generated by default on null as identity';
end;
/

prompt -- trigger HOM_ICONS_AUDIT
@@ddl/triggers/hom_icons_audit.sql
show errors

prompt -- packages
@@packages/pck_hom_log.sql
show errors
@@packages/pck_hom_config_dml.sql
show errors
@@packages/pck_hom_categories_dml.sql
show errors
@@packages/pck_hom_icons_dml.sql
show errors
@@packages/pck_hom_app_config_dml.sql
show errors
@@packages/pck_hom_links_dml.sql
show errors
@@packages/pck_hom_api.sql
show errors

prompt -- views
@@views/hom_views.sql
show errors

prompt -- top up any newly added default config keys (existing values preserved)
begin
  pck_hom_config_dml.init_defaults;
  commit;
end;
/

prompt ORAHomer updated.
